### ISSUE TITLE
Add citation to Brick Schema

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-usecases#121]
The Brick Schema (https://brickschema.org/) is an RDF-based ontology for smart building applications.  It seems like it would be a natural fit for some WoT use cases (e.g. linked buildings).   We should investigate, and if it seems applicable, add it as a citation under the appropriate use cases.

**Comment by sebastiankb** [comment]
The PR https://github.com/w3c/wot-usecases/pull/102 also use the brick ontology. Maybe @GeorgFerdinandSchneider can comment on this.

**Comment by GeorgFerdinandSchneider** [comment]
Dear @sebastiankb ,

indeed we use it in the use case described in #102. @gtfierro is the lead developer of BRICK - I am sure he is happy to provide details on BRICK as needed.

Best

**Comment by gtfierro** [comment]
Thanks for the ping, @GeorgFerdinandSchneider! I would be happy to contribute additional use cases and requirements that reflect our experiences with Brick. Let me know if there is anything specific you'd like my input on, but I should be able to add some content by the end of the week.

**Comment by mlagally** [comment]
@gtfierro 
It would be nice if you would contribute your use case(s), which should go into the next release of the document.

**Comment by gtfierro** [comment]
I've written up a use case focusing on integration between WoT and Brick [here](https://github.com/w3c/wot-usecases/pull/132). Happy to take comments, suggestions, questions and critiques!

**Comment by mlagally** [comment]
Editorial: add a specref reference
