### ISSUE TITLE
Read-through rendered document

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-usecases#123]
I read through the [Use Cases and Requirements](https://w3c.github.io/wot-usecases/) document and I stumbled over some typos et cetera. see https://github.com/w3c/wot-usecases/pull/122
Note: Please check yourself before approving!

Moreover, I noticed some other discrepancies but I am not sure whether they can (should) be aligned
* standardisation vs standardization 
* Internationalisation vs internationalization
* behaviour vs. behavior 
* decentralised vs decentralized 
* e.g. vs eg
* etc vs. etc.

**Comment by mlagally** [comment]
The W3C manual of style uses US english: https://www.w3.org/Guide/manual-of-style/
I applied these fixes in #125
