### ISSUE TITLE
Revise introductory Retail use case - table, etc.

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-usecases#172]
When we merged the new retail use cases we had to figure out what to do with the old singleton use case and the introductory material for the new use cases, including a table comparing them.  For now we put all use cases in a flat structure and commented out the table, but perhaps the table should be merged into the first use case (and the first use case should be aligned and updated as a summary or overview of the rest)

**Comment by mlagally** [comment]
UC call on Jan 11th.
Decide to not add new text.
