### ISSUE TITLE
[UC Template] Typos

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-usecases#288]
* Stackholder -> Stakeholder
* descrive -> describe
* eyour -> your
* "X as a guide" -> "X" (under Security, Privacy, etc).  More to say about this in another issue, here I just am trying to fix typos.
     * Under Security Considerations, "See also the security part of"
* " Clarificaitons on" -> "Clarifications of"

**Comment by egekorkan** [comment]
Points 1, 2, and 5 are done as part of #285

**Comment by chachamimm** [comment]
closed
