### ISSUE TITLE
Complete privacy section for Medical use case

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-usecases#50]
The Medical use case currently has an empty Privacy section but mentions privacy-related standards (eg HIPAA) under Security.   This should be cleaned up.

**Comment by mlagally** [comment]
UC call on Jan 11th:
Proposed text: Medical applications need to be conformant with the appropriate medical privacy standards.

**Comment by mmccool** [comment]
PR #175 now addresses this issue as stated (in addition to HIPAA also added references to GDPR and PIPEDA) but there are other standards cited in the ICU Health monitoring use case that should be turned into references (but as this is a general problem, deferred to Issue dealing with this generally)
