### ISSUE TITLE
Fix reference section

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-usecases#70]
Respec manages external references.

https://respec.org/docs/

https://respec.org/docs/#references

Examples: TD or Architecture, Profile

**Comment by chachamimm** [comment]
I created Pull Request.

I rewrote the reference section to fix the respec format and move <head> section.

But there were not enough the information of each references. I add the information that I was able to look up. But it was not enough.

**Comment by mlagally** [comment]
Some local references are probably in the SpecRef database, some others are missing content, e.g. MMI references.

**Comment by mlagally** [comment]
I cleaned up the references section, MR: #129
